### ISSUE TITLE
package for multiple ubuntu distro codenames

### ISSUE THREAD

**Issue by FeignInt** [FeignInt/dosbox-staging-deb#2]
see if I can get PPA to build for multiple distributions

It would be nice as I can then drop my hacky min. version strip in `debian/rules` 

@soredake
dosbox-staging/dosbox-staging#418

**Comment by soredake** [comment]
Installed `devscripts equivs`, changed command `sudo mk-build-dep` to `sudo mk-build-deps` because `mk-build-dep` does not exists, now getting this:
```
❯ sudo mk-build-deps -i dosbox-staging
W: Unable to locate package dosbox-staging
mk-build-deps: Unable to find package name in `apt-cache showsrc dosbox-staging'
```

**Comment by FeignInt** [comment]
ahhh, ok I see the problem
```
cat /etc/apt/sources.list.d/feignint-ubuntu-dosbox-staging-bionic.list 
deb http://ppa.launchpad.net/feignint/dosbox-staging/ubuntu bionic main
# deb-src http://ppa.launchpad.net/feignint/dosbox-staging/ubuntu bionic main
```
either, manually un-comment that line and apt update, or
```
sudo add-apt-repository -s ppa:feignint/dosbox-staging
```
the -s is **`--enable-source   Allow downloading of the source packages from the repository`**

I will add that to the README

Thanks: @soredake

**Comment by soredake** [comment]
I used -s option when adding ppa, but i'm on focal, ppa does not have any package for focal, source or not.

**Comment by FeignInt** [comment]
I assume that /etc/apt/sources.list.d/feignint-ubuntu-dosbox-staging-focal.list exists
and it contains
```
deb http://ppa.launchpad.net/feignint/dosbox-staging/ubuntu focal main
deb-src http://ppa.launchpad.net/feignint/dosbox-staging/ubuntu focal main
```
make a copy of that file in /etc/apt/sources.list.d/ and change focal to bionic

https://launchpad.net/~feignint/+archive/ubuntu/dosbox-staging
> **Technical details about this PPA**
This PPA can be added to your system manually by copying the lines below and adding them to your system's software sources.
>
>    deb http://ppa.launchpad.net/feignint/dosbox-staging/ubuntu bionic main 
>    deb-src http://ppa.launchpad.net/feignint/dosbox-staging/ubuntu bionic main

**Comment by FeignInt** [comment]
as you can probably tell, I don't use Ubuntu, in Debian we just edit files :smiley: 

edit: that distro bit does not work as I expected, although my current guess is it would work if more than one codename available.

span up ubuntu in lxc again
apt-add-repository --help
:scissors: 
  Examples:
    :scissors: 
    apt-add-repository ppa:user/repository
    apt-add-repository ppa:user/**distro**/repository
    apt-add-repository multiverse
:scissors: 
```

**Comment by soredake** [comment]
Compilation works fine after changing to bionic

**Comment by DOOMMARINE117** [comment]
i see yoru updating more files. should i install it to doosbox staging folder?

**Comment by FeignInt** [comment]
@DOOMMARINE117 which Linux distro do you use?

your past posts appear to be related to Windows10

**Comment by DOOMMARINE117** [comment]
> 
> 
> @DOOMMARINE117 which Linux distro do you use?
> 
> your past posts appear to be related to Windows10

this for linux? not windows 10? lol. good thing i hadn't installed this yet, lol.
